apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homelab-analytics.fullname" . }}-config
  labels:
    {{- include "homelab-analytics.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.commonEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
