{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homelab-analytics.fullname" . }}-web
  labels:
    {{- include "homelab-analytics.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "homelab-analytics.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "homelab-analytics.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "homelab-analytics.serviceAccountName" . }}
      containers:
        - name: web
          image: "{{ .Values.webImage.repository }}:{{ .Values.webImage.tag }}"
          imagePullPolicy: {{ .Values.webImage.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: {{ include "homelab-analytics.fullname" . }}-config
            {{- range .Values.web.secretEnvFrom }}
            - secretRef:
                name: {{ . | quote }}
            {{- end }}
          env:
            - name: HOMELAB_ANALYTICS_API_BASE_URL
              value: {{ printf "http://%s-api:%v" (include "homelab-analytics.fullname" .) .Values.api.port | quote }}
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "homelab-analytics.dataClaimName" . }}
{{- end }}
