"""Finance domain capability pack manifest — declares sources, workflows, and publications."""
from __future__ import annotations

from packages.domains.finance.sources.account_transactions import ACCOUNT_TRANSACTIONS_SOURCE
from packages.domains.finance.sources.subscriptions import SUBSCRIPTIONS_SOURCE
from packages.platform.capability_types import (
    CapabilityPack,
    PublicationDefinition,
    UiDescriptor,
    WorkflowDefinition,
)

FINANCE_PACK = CapabilityPack(
    name="finance",
    version="1.0.0",
    sources=(
        ACCOUNT_TRANSACTIONS_SOURCE,
        SUBSCRIPTIONS_SOURCE,
    ),
    workflows=(
        WorkflowDefinition(
            workflow_id="ingest-account-transactions",
            display_name="Ingest Account Transactions",
            source_dataset_name="account_transactions",
            retry_policy="always",
            idempotency_mode="run_id",
            required_permissions=("operator",),
            command_name="ingest-account-transactions",
            publication_keys=(
                "monthly_cashflow",
                "spend_by_category_monthly",
                "recent_large_transactions",
                "account_balance_trend",
                "transaction_anomalies_current",
            ),
            identity_strategy_id="bank_transaction_v1",
        ),
        WorkflowDefinition(
            workflow_id="ingest-subscriptions",
            display_name="Ingest Subscriptions",
            source_dataset_name="subscriptions",
            retry_policy="always",
            idempotency_mode="run_id",
            required_permissions=("operator",),
            command_name="ingest-subscriptions",
            publication_keys=("subscription_summary", "upcoming_fixed_costs_30d"),
        ),
        WorkflowDefinition(
            workflow_id="ingest-configured-csv",
            display_name="Ingest Configured CSV",
            source_dataset_name="configured_csv",
            retry_policy="always",
            idempotency_mode="run_id",
            required_permissions=("operator",),
            command_name="ingest-configured-csv",
            publication_keys=(),
        ),
    ),
    publications=(
        PublicationDefinition(
            key="monthly_cashflow",
            schema_name="monthly_cashflow",
            display_name="Monthly Cashflow",
            description="Aggregated monthly income and expense summary from account transactions.",
            visibility="public",
            lineage_required=True,
            retention_policy="indefinite",
        ),
        PublicationDefinition(
            key="subscription_summary",
            schema_name="subscription_summary",
            display_name="Subscription Summary",
            description="Active recurring subscription costs grouped by category.",
            visibility="public",
            lineage_required=True,
            retention_policy="indefinite",
        ),
        PublicationDefinition(
            key="spend_by_category_monthly",
            schema_name="spend_by_category_monthly",
            display_name="Spend by Category Monthly",
            description="Monthly expense totals grouped by counterparty and category.",
            visibility="public",
            lineage_required=True,
            retention_policy="indefinite",
        ),
        PublicationDefinition(
            key="recent_large_transactions",
            schema_name="recent_large_transactions",
            display_name="Recent Large Transactions",
            description="Notable transactions above a threshold in recent months.",
            visibility="public",
            lineage_required=True,
            retention_policy="rolling_12_months",
        ),
        PublicationDefinition(
            key="account_balance_trend",
            schema_name="account_balance_trend",
            display_name="Account Balance Trend",
            description="Cumulative balance trend per account derived from transaction history.",
            visibility="public",
            lineage_required=True,
            retention_policy="indefinite",
        ),
        PublicationDefinition(
            key="transaction_anomalies_current",
            schema_name="transaction_anomalies_current",
            display_name="Transaction Anomalies",
            description="Recent transactions flagged as anomalous — first-time counterparties or unusual amounts.",
            visibility="public",
            lineage_required=True,
            retention_policy="rolling_12_months",
        ),
        PublicationDefinition(
            key="upcoming_fixed_costs_30d",
            schema_name="upcoming_fixed_costs_30d",
            display_name="Upcoming Fixed Costs (30 days)",
            description="Active recurring subscriptions projected as upcoming charges in the next 30 days.",
            visibility="public",
            lineage_required=True,
            retention_policy="rolling_12_months",
        ),
    ),
    ui_descriptors=(
        UiDescriptor(
            key="cashflow",
            nav_label="Cashflow",
            nav_path="/reports/cashflow",
            kind="dashboard",
            publication_keys=("monthly_cashflow",),
            icon="chart-bar",
        ),
        UiDescriptor(
            key="subscriptions",
            nav_label="Subscriptions",
            nav_path="/reports/subscriptions",
            kind="report",
            publication_keys=("subscription_summary",),
            icon="repeat",
        ),
        UiDescriptor(
            key="spending-by-category",
            nav_label="Spending by Category",
            nav_path="/reports/spending-by-category",
            kind="report",
            publication_keys=("spend_by_category_monthly",),
            icon="pie-chart",
        ),
        UiDescriptor(
            key="large-transactions",
            nav_label="Large Transactions",
            nav_path="/reports/large-transactions",
            kind="table",
            publication_keys=("recent_large_transactions",),
            icon="alert-circle",
        ),
        UiDescriptor(
            key="balance-trend",
            nav_label="Balance Trend",
            nav_path="/reports/balance-trend",
            kind="dashboard",
            publication_keys=("account_balance_trend",),
            icon="trending-up",
        ),
        UiDescriptor(
            key="anomalies",
            nav_label="Anomalies",
            nav_path="/reports/anomalies",
            kind="table",
            publication_keys=("transaction_anomalies_current",),
            icon="alert-triangle",
        ),
        UiDescriptor(
            key="upcoming-costs",
            nav_label="Upcoming Costs",
            nav_path="/reports/upcoming-costs",
            kind="table",
            publication_keys=("upcoming_fixed_costs_30d",),
            icon="calendar",
        ),
    ),
)
